version: "3.2"
services:
  goalfeed-go:
    build: .
    env_file: .env
    network_mode: host
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass testpass
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis-data:/var/lib/redis
      - ./storage/redis.conf:/usr/local/etc/redis/redis.conf
