name: Build and Version Bump

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Bump version and push tag
        id: bump-version
        run: |
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # If on main branch, increment the patch version
            newTag=$(echo $latestTag | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          else
            # If on another branch, append the branch name to the version
            branchName=$(echo "${{ github.ref }}" | sed -r "s/refs\/heads\///g" | sed "s/\//-/g")
            newTag="${latestTag}-${branchName}"
          fi
          
          git tag $newTag
          git push origin $newTag
          echo "NEW_TAG=${newTag}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com

      - name: Build
        run: go build -ldflags "-X main.version=${NEW_TAG}" -o goalfeed

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: goalfeed-binary
          path: ./goalfeed
