name: GoReleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install GoReleaser
        run: |
          curl -sSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

      - name: Run GoReleaser
        run: |
          ./bin/goreleaser release --rm-dist

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist

